<?php
/**
 * Generated AST Converter
 * DO NOT EDIT - Generated by ConverterGenerator
 */

namespace PESM\Parser;

use PESM\Parser\AST\Node;
use PESM\Parser\AST\VariableNode;

class GeneratedConverter
{
        /**
     * Convert parse result array to AST
     */
    public function convert($data): \PESM\Parser\AST\Node
    {
        if (!is_array($data)) {
            throw new \Exception("Invalid parse result");
        }
        
        // Unwrap Statement to node if present
        if (isset($data['_matchrule']) && $data['_matchrule'] === 'Statement' && isset($data['node'])) {
            $data = $data['node'];
        }
        
        // Unwrap Statement to alt if present (PESM style)
        if (isset($data['_matchrule']) && $data['_matchrule'] === 'Statement' && isset($data['alt'])) {
            $data = $data['alt'];
        }
        
        // Detect rule type from array structure
        $type = $this->detectType($data);
        $method = 'convert' . $type;
        
        if (!method_exists($this, $method)) {
            // No converter - try to unwrap to child
            return $this->unwrap($data);
        }
        
        return $this->$method($data);
    }
    
    /**
     * Unwrap intermediate nodes without converters
     */
    private function unwrap(array $data): \PESM\Parser\AST\Node
    {
        $type = $data['_matchrule'] ?? '';
        
        // Special handling for binary operations
        if (in_array($type, ['Additive', 'Multiplicative', 'Expression', 'Logical', 'Comparison'])) {
            // If has ops, build BinaryOpNode
            if (isset($data['ops']) && !empty($data['ops'])) {
                $left = $this->convert($data['left']);
                foreach ($data['ops'] as $i => $op) {
                    $right = $this->convert($data['rights'][$i]);
                    $left = new \PESM\Parser\AST\BinaryOpNode($left, $op['text'], $right);
                }
                return $left;
            }
            // No ops, unwrap to child
            if (isset($data['left'])) {
                return $this->convert($data['left']);
            }
            if (isset($data['value'])) {
                return $this->convert($data['value']);
            }
        }
        
        // Special handling for Unary
        if ($type === 'Unary') {
            if (isset($data['operator']) && isset($data['expr'])) {
                return new \PESM\Parser\AST\UnaryOpNode($data['operator'], $this->convert($data['expr']));
            }
            if (isset($data['node'])) {
                return $this->convert($data['node']);
            }
        }
        
        // Special handling for Postfix
        if ($type === 'Postfix') {
            if (isset($data['indices']) && !empty($data['indices'])) {
                $base = $this->convert($data['base']);
                foreach ($data['indices'] as $idx) {
                    $indexNode = $this->convert($idx);
                    $base = new \PESM\Parser\AST\ArrayAccessNode($base, $indexNode);
                }
                return $base;
            }
            if (isset($data['base'])) {
                return $this->convert($data['base']);
            }
        }
        
        // Try to find first child node
        foreach ($data as $key => $value) {
            if ($key !== 'text' && $key !== '_matchrule' && $key !== 'name' && $key !== 'offset' && is_array($value)) {
                return $this->convert($value);
            }
        }
        throw new \Exception("Cannot unwrap node: " . json_encode($data));
    }
    
    /**
     * Detect rule type from array structure
     */
    private function detectType(array $data): string
    {
        // Check for _matchrule key (generated by parser)
        if (isset($data['_matchrule'])) {
            $type = $data['_matchrule'];
            
            // If it's Statement with node (BASIC style), unwrap to node
            if ($type === 'Statement' && isset($data['node'])) {
                return $this->detectType($data['node']);
            }
            
            // If it's Statement with alt (PESM style), unwrap to alt
            if ($type === 'Statement' && isset($data['alt'])) {
                return $this->detectType($data['alt']);
            }
            
            return $type;
        }
        
        // Check for known keys
        $keys = array_keys($data);
        foreach ($keys as $key) {
            if ($key !== 'text' && !is_numeric($key)) {
                return $key;
            }
        }
        
        // Fallback to text-based detection
        if (isset($data['text'])) {
            $text = $data['text'];
            if (preg_match('/^[a-zA-Z_]/', $text)) {
                return 'Identifier';
            }
            if (is_numeric($text)) {
                return 'Number';
            }
        }
        
        throw new \Exception("Cannot detect type from data: " . json_encode($data));
    }
    
    /**
     * Extract value from data, converting if needed
     */
    private function extractValue(array $data, string $key)
    {
        if (isset($data[$key])) {
            $value = $data[$key];
            if (is_array($value)) {
                return $this->convert($value);
            }
            return $value;
        }
        
        // Try to find in nested structure
        foreach ($data as $k => $v) {
            if (is_array($v) && isset($v[$key])) {
                return $this->extractValue($v, $key);
            }
        }
        
        return null;
    }
    
    /**
     * Extract all arguments from data
     */
    private function extractArguments(array $data): array
    {
        $args = [];
        foreach ($data as $key => $value) {
            if ($key === 'text' || $key === '_matchrule' || $key === 'name' || $key === 'offset') continue;
            if (is_numeric($key)) continue;
            
            if (is_array($value)) {
                $args[] = $this->convert($value);
            } else {
                $args[] = $value;
            }
        }
        return $args;
    }
    
    /**
     * Extract arguments for interrupt statements
     * Handles special format: type stored in 'interruptType', expr, and optional var
     */
    private function extractInterruptArguments(array $data): array
    {
        $args = [];
        
        // First argument: type (stored in 'interruptType' field by grammar callback)
        $args[] = $data['interruptType'];
        
        // Second argument: expr (convert to AST node)
        $args[] = $this->convert($data['expr']['value'] ?? $data['expr']);
        
        // Third argument: var (optional, only for InterruptWithVarStmt)
        if (isset($data['var'])) {
            $varNode = $this->convert($data['var']);
            $args[] = $varNode->name;
        }
        
        return $args;
    }
    
    /**
     * Extract arguments for FOREACH statements
     * ForeachInStmt: var, iterable, body
     * ForeachRangeStmt: var, BinaryOpNode(from, 'range', to), body
     */
    private function extractForeachArguments(array $data, string $rule): array
    {
        $args = [];
        
        // First argument: var name
        $varNode = $this->convert($data['var']);
        $args[] = $varNode->name;
        
        // Second argument: iterable or range
        if ($rule === 'ForeachInStmt') {
            // Direct iterable
            $args[] = $this->convert($data['iterable']['value'] ?? $data['iterable']);
        } else {
            // ForeachRangeStmt: create BinaryOpNode for range
            $from = $this->convert($data['from']['value'] ?? $data['from']);
            $to = $this->convert($data['to']['value'] ?? $data['to']);
            $args[] = new \PESM\Parser\AST\BinaryOpNode($from, 'range', $to);
        }
        
        // Third argument: body (loop statements)
        $body = [];
        if (isset($data['loopBody'])) {
            foreach ($data['loopBody'] as $stmt) {
                $node = isset($stmt['node']) ? $stmt['node'] : $stmt;
                $body[] = $this->convert($node);
            }
        }
        $args[] = $body;
        
        return $args;
    }
    
    /**
     * Extract arguments for SWITCH statement
     * SwitchStatement: expr, cases, defaultBody
     * cases is array of ['value' => Node, 'body' => [Node, ...]]
     */
    private function extractSwitchArguments(array $data): array
    {
        $args = [];
        
        // First argument: switch expression
        $args[] = $this->convert($data['expr']['value'] ?? $data['expr']);
        
        // Second argument: cases array
        $cases = [];
        if (isset($data['cases'])) {
            foreach ($data['cases'] as $caseData) {
                $caseValue = $this->convert($caseData['value']['value'] ?? $caseData['value']);
                $caseBody = [];
                if (isset($caseData['caseBody'])) {
                    foreach ($caseData['caseBody'] as $stmt) {
                        $node = isset($stmt['node']) ? $stmt['node'] : $stmt;
                        $caseBody[] = $this->convert($node);
                    }
                }
                $cases[] = ['value' => $caseValue, 'body' => $caseBody];
            }
        }
        $args[] = $cases;
        
        // Third argument: default body
        $defaultBody = [];
        if (isset($data['defaultCase']['defaultBody'])) {
            foreach ($data['defaultCase']['defaultBody'] as $stmt) {
                $node = isset($stmt['node']) ? $stmt['node'] : $stmt;
                $defaultBody[] = $this->convert($node);
            }
        }
        $args[] = $defaultBody;
        
        return $args;
    }
}
