<?php

namespace PESM\Parser;

/**
 * ConverterGenerator - Generates AST Builder from grammar metadata
 */
class ConverterGenerator
{
    private array $metadata;
    
    public function __construct(array $metadata)
    {
        $this->metadata = $metadata;
    }
    
    /**
     * Generate complete converter class
     */
    public function generate(): string
    {
        $code = $this->generateHeader();
        $code .= $this->generateMainMethod();
        
        foreach ($this->metadata as $rule => $info) {
            if ($info['node']) {
                $code .= $this->generateConvertMethod($rule, $info);
            }
        }
        
        $code .= $this->generateHelpers();
        $code .= "}\n";
        
        return $code;
    }
    
    /**
     * Generate class header
     */
    private function generateHeader(): string
    {
        $nodes = array_unique(array_column(array_filter($this->metadata, fn($r) => $r['node']), 'node'));
        $uses = implode("\n", array_map(fn($n) => "use PESM\\Parser\\AST\\{$n};", $nodes));
        
        return <<<PHP
<?php
/**
 * Generated AST Converter
 * DO NOT EDIT - Generated by ConverterGenerator
 */

namespace PESM\\Parser;

use PESM\\Parser\\AST\\Node;
{$uses}

class GeneratedConverter
{
    
PHP;
    }
    
    /**
     * Generate main convert method
     */
    private function generateMainMethod(): string
    {
        return <<<'PHP'
    /**
     * Convert parse result array to AST
     */
    public function convert($data): \PESM\Parser\AST\Node
    {
        if (!is_array($data)) {
            throw new \Exception("Invalid parse result");
        }
        
        // Unwrap Statement to alt if present
        if (isset($data['_matchrule']) && $data['_matchrule'] === 'Statement' && isset($data['alt'])) {
            $data = $data['alt'];
        }
        
        // Detect rule type from array structure
        $type = $this->detectType($data);
        $method = 'convert' . $type;
        
        if (!method_exists($this, $method)) {
            // No converter - try to unwrap to child
            return $this->unwrap($data);
        }
        
        return $this->$method($data);
    }
    
    /**
     * Unwrap intermediate nodes without converters
     */
    private function unwrap(array $data): \PESM\Parser\AST\Node
    {
        // Try to find first child node
        foreach ($data as $key => $value) {
            if ($key !== 'text' && $key !== '_matchrule' && $key !== 'name' && $key !== 'offset' && is_array($value)) {
                return $this->convert($value);
            }
        }
        throw new \Exception("Cannot unwrap node: " . json_encode($data));
    }
    

PHP;
    }
    
    /**
     * Generate convert method for specific rule
     */
    private function generateConvertMethod(string $rule, array $info): string
    {
        $nodeClass = $info['node'];
        $args = $info['args'] ?? [];
        
        $code = "    /**\n";
        $code .= "     * Convert $rule to $nodeClass\n";
        $code .= "     */\n";
        $code .= "    private function convert{$rule}(array \$data): \\PESM\\Parser\\AST\\{$nodeClass}\n";
        $code .= "    {\n";
        
        // Special case for Assignment
        if ($rule === 'Assignment') {
            $code .= "        \$varNode = \$this->convert(\$data['var']);\n";
            $code .= "        \$exprNode = \$data['expr']['value'] ?? \$data['expr'];\n";
            $code .= "        \$exprNode = \$this->convert(\$exprNode);\n";
            $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(\$varNode->name, \$exprNode);\n";
            $code .= "    }\n\n";
            return $code;
        }
        
        // Generate conversion logic based on rule type
        switch ($info['type']) {
            case 'regex':
                $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(\$data['text']);\n";
                break;
                
            case 'oneOrMore':
            case 'zeroOrMore':
                $code .= "        \$items = [];\n";
                $code .= "        if (isset(\$data['statements'])) {\n";
                $code .= "            foreach (\$data['statements'] as \$stmt) {\n";
                $code .= "                \$node = isset(\$stmt['node']) ? \$stmt['node'] : \$stmt;\n";
                $code .= "                \$items[] = \$this->convert(\$node);\n";
                $code .= "            }\n";
                $code .= "        }\n";
                $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(\$items);\n";
                break;
                
            case 'choice':
                $code .= "        // Handle choice - unwrap to actual alternative\n";
                $code .= "        foreach (\$data as \$key => \$value) {\n";
                $code .= "            if (\$key !== 'text' && \$key !== '_matchrule' && \$key !== 'name' && \$key !== 'offset' && is_array(\$value)) {\n";
                $code .= "                return \$this->convert(\$value);\n";
                $code .= "            }\n";
                $code .= "        }\n";
                $code .= "        throw new \\Exception('No valid alternative found in choice');\n";
                break;
                
            default:
                // Sequence - extract components
                if (!empty($args)) {
                    $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(\n";
                    $argsList = [];
                    foreach ($args as $arg) {
                        $argsList[] = "            \$this->extractValue(\$data, '$arg')";
                    }
                    $code .= implode(",\n", $argsList) . "\n";
                    $code .= "        );\n";
                } else {
                    // Auto-detect arguments
                    $code .= "        \$args = \$this->extractArguments(\$data);\n";
                    $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(...\$args);\n";
                }
        }
        
        $code .= "    }\n\n";
        
        return $code;
    }
    
    /**
     * Generate helper methods
     */
    private function generateHelpers(): string
    {
        return <<<'PHP'
    /**
     * Detect rule type from array structure
     */
    private function detectType(array $data): string
    {
        // Check for _matchrule key (generated by parser)
        if (isset($data['_matchrule'])) {
            $type = $data['_matchrule'];
            
            // If it's Statement (choice without node), unwrap to alt
            if ($type === 'Statement' && isset($data['alt'])) {
                return $this->detectType($data['alt']);
            }
            
            return $type;
        }
        
        // Check for known keys
        $keys = array_keys($data);
        foreach ($keys as $key) {
            if ($key !== 'text' && !is_numeric($key)) {
                return $key;
            }
        }
        
        // Fallback to text-based detection
        if (isset($data['text'])) {
            $text = $data['text'];
            if (preg_match('/^[a-zA-Z_]/', $text)) {
                return 'Identifier';
            }
            if (is_numeric($text)) {
                return 'Number';
            }
        }
        
        throw new \Exception("Cannot detect type from data: " . json_encode($data));
    }
    
    /**
     * Extract value from data, converting if needed
     */
    private function extractValue(array $data, string $key)
    {
        if (isset($data[$key])) {
            $value = $data[$key];
            if (is_array($value)) {
                return $this->convert($value);
            }
            return $value;
        }
        
        // Try to find in nested structure
        foreach ($data as $k => $v) {
            if (is_array($v) && isset($v[$key])) {
                return $this->extractValue($v, $key);
            }
        }
        
        return null;
    }
    
    /**
     * Extract all arguments from data
     */
    private function extractArguments(array $data): array
    {
        $args = [];
        foreach ($data as $key => $value) {
            if ($key === 'text' || $key === '_matchrule' || $key === 'name' || $key === 'offset') continue;
            if (is_numeric($key)) continue;
            
            if (is_array($value)) {
                $args[] = $this->convert($value);
            } else {
                $args[] = $value;
            }
        }
        return $args;
    }

PHP;
    }
}
