<?php

namespace PESM\Parser;

/**
 * ConverterGenerator - Generates AST Builder from grammar metadata
 */
class ConverterGenerator
{
    private array $metadata;
    
    public function __construct(array $metadata)
    {
        $this->metadata = $metadata;
    }
    
    /**
     * Generate complete converter class
     */
    public function generate(): string
    {
        $code = $this->generateHeader();
        $code .= $this->generateMainMethod();
        
        foreach ($this->metadata as $rule => $info) {
            if ($info['node']) {
                $code .= $this->generateConvertMethod($rule, $info);
            }
        }
        
        $code .= $this->generateHelpers();
        $code .= "}\n";
        
        return $code;
    }
    
    /**
     * Generate class header
     */
    private function generateHeader(): string
    {
        $nodes = array_unique(array_column(array_filter($this->metadata, fn($r) => $r['node']), 'node'));
        $uses = implode("\n", array_map(fn($n) => "use PESM\\Parser\\AST\\{$n};", $nodes));
        
        return <<<PHP
<?php
/**
 * Generated AST Converter
 * DO NOT EDIT - Generated by ConverterGenerator
 */

namespace PESM\\Parser;

use PESM\\Parser\\AST\\Node;
{$uses}

class GeneratedConverter
{
    
PHP;
    }
    
    /**
     * Generate main convert method
     */
    private function generateMainMethod(): string
    {
        return <<<'PHP'
    /**
     * Convert parse result array to AST
     */
    public function convert($data): \PESM\Parser\AST\Node
    {
        if (!is_array($data)) {
            throw new \Exception("Invalid parse result");
        }
        
        // Unwrap Statement to alt if present
        if (isset($data['_matchrule']) && $data['_matchrule'] === 'Statement' && isset($data['alt'])) {
            $data = $data['alt'];
        }
        
        // Detect rule type from array structure
        $type = $this->detectType($data);
        $method = 'convert' . $type;
        
        if (!method_exists($this, $method)) {
            // No converter - try to unwrap to child
            return $this->unwrap($data);
        }
        
        return $this->$method($data);
    }
    
    /**
     * Unwrap intermediate nodes without converters
     */
    private function unwrap(array $data): \PESM\Parser\AST\Node
    {
        $type = $data['_matchrule'] ?? '';
        
        // Special handling for binary operations
        if (in_array($type, ['Additive', 'Multiplicative', 'Expression', 'Logical', 'Comparison'])) {
            // If has ops, build BinaryOpNode
            if (isset($data['ops']) && !empty($data['ops'])) {
                $left = $this->convert($data['left']);
                foreach ($data['ops'] as $i => $op) {
                    $right = $this->convert($data['rights'][$i]);
                    $left = new \PESM\Parser\AST\BinaryOpNode($left, $op['text'], $right);
                }
                return $left;
            }
            // No ops, unwrap to child
            if (isset($data['left'])) {
                return $this->convert($data['left']);
            }
            if (isset($data['value'])) {
                return $this->convert($data['value']);
            }
        }
        
        // Try to find first child node
        foreach ($data as $key => $value) {
            if ($key !== 'text' && $key !== '_matchrule' && $key !== 'name' && $key !== 'offset' && is_array($value)) {
                return $this->convert($value);
            }
        }
        throw new \Exception("Cannot unwrap node: " . json_encode($data));
    }
    

PHP;
    }
    
    /**
     * Generate convert method for specific rule
     */
    private function generateConvertMethod(string $rule, array $info): string
    {
        $nodeClass = $info['node'];
        $args = $info['args'] ?? [];
        
        $code = "    /**\n";
        $code .= "     * Convert $rule to $nodeClass\n";
        $code .= "     */\n";
        $code .= "    private function convert{$rule}(array \$data): \\PESM\\Parser\\AST\\{$nodeClass}\n";
        $code .= "    {\n";
        
        // Special case for Assignment
        if ($rule === 'Assignment') {
            $code .= "        \$varNode = \$this->convert(\$data['var']);\n";
            $code .= "        \$exprNode = \$data['expr']['value'] ?? \$data['expr'];\n";
            $code .= "        \$exprNode = \$this->convert(\$exprNode);\n";
            $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(\$varNode->name, \$exprNode);\n";
            $code .= "    }\n\n";
            return $code;
        }
        
        // Special case for String
        if ($rule === 'String') {
            $code .= "        \$value = \$data['value'] ?? \$data['text'];\n";
            $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(\$value);\n";
            $code .= "    }\n\n";
            return $code;
        }
        
        // Special case for IfStatement
        if ($rule === 'IfStatement') {
            $code .= "        \$cond = \$this->convert(\$data['cond']['value'] ?? \$data['cond']);\n";
            $code .= "        \$thenBody = [];\n";
            $code .= "        if (isset(\$data['thenBody'])) {\n";
            $code .= "            foreach (\$data['thenBody'] as \$stmt) {\n";
            $code .= "                \$node = isset(\$stmt['node']) ? \$stmt['node'] : \$stmt;\n";
            $code .= "                \$thenBody[] = \$this->convert(\$node);\n";
            $code .= "            }\n";
            $code .= "        }\n";
            $code .= "        \$elseBody = [];\n";
            $code .= "        if (isset(\$data['elseBody'])) {\n";
            $code .= "            foreach (\$data['elseBody'] as \$stmt) {\n";
            $code .= "                \$node = isset(\$stmt['node']) ? \$stmt['node'] : \$stmt;\n";
            $code .= "                \$elseBody[] = \$this->convert(\$node);\n";
            $code .= "            }\n";
            $code .= "        }\n";
            $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(\$cond, \$thenBody, \$elseBody);\n";
            $code .= "    }\n\n";
            return $code;
        }
        
        // Special case for ForeachStatement
        if ($rule === 'ForeachStatement') {
            $code .= "        \$varNode = \$this->convert(\$data['var']);\n";
            $code .= "        \$from = \$this->convert(\$data['from']['value'] ?? \$data['from']);\n";
            $code .= "        \$to = \$this->convert(\$data['to']['value'] ?? \$data['to']);\n";
            $code .= "        \$body = [];\n";
            $code .= "        if (isset(\$data['loopBody'])) {\n";
            $code .= "            foreach (\$data['loopBody'] as \$stmt) {\n";
            $code .= "                \$node = isset(\$stmt['node']) ? \$stmt['node'] : \$stmt;\n";
            $code .= "                \$body[] = \$this->convert(\$node);\n";
            $code .= "            }\n";
            $code .= "        }\n";
            $code .= "        // ForeachNode expects (var, iterable, body) but grammar has from/to\n";
            $code .= "        // Create range array\n";
            $code .= "        return new \\PESM\\Parser\\AST\\ForeachNode(\$varNode->name, new \\PESM\\Parser\\AST\\BinaryOpNode(\$from, 'range', \$to), \$body);\n";
            $code .= "    }\n\n";
            return $code;
        }
        
        // Special case for FunctionCall
        if ($rule === 'FunctionCall') {
            $code .= "        \$nameNode = \$this->convert(\$data['fname']);\n";
            $code .= "        \$args = [];\n";
            $code .= "        if (isset(\$data['args'])) {\n";
            $code .= "            // args can be single Expression or array\n";
            $code .= "            \$argData = is_array(\$data['args']) && isset(\$data['args'][0]) ? \$data['args'] : [\$data['args']];\n";
            $code .= "            foreach (\$argData as \$arg) {\n";
            $code .= "                if (is_array(\$arg) && isset(\$arg['_matchrule'])) {\n";
            $code .= "                    \$args[] = \$this->convert(\$arg);\n";
            $code .= "                }\n";
            $code .= "            }\n";
            $code .= "        }\n";
            $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(\$nameNode->name, \$args);\n";
            $code .= "    }\n\n";
            return $code;
        }
        
        // Special case for MessageStmt/AcceptStmt/RefuseStmt
        if (in_array($rule, ['MessageStmt', 'AcceptStmt', 'RefuseStmt'])) {
            $key = $rule === 'MessageStmt' ? 'msg' : 'state';
            $code .= "        \$arg = isset(\$data['$key']) ? \$this->convert(\$data['$key']) : null;\n";
            $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(\$arg);\n";
            $code .= "    }\n\n";
            return $code;
        }
        
        // Special case for binary operations (Additive, Multiplicative)
        if (in_array($rule, ['Additive', 'Multiplicative'])) {
            $code .= "        // Build binary operation tree\n";
            $code .= "        \$left = \$this->convert(\$data['left']);\n";
            $code .= "        if (!isset(\$data['ops']) || empty(\$data['ops'])) {\n";
            $code .= "            return \$left; // No operation, just return left\n";
            $code .= "        }\n";
            $code .= "        foreach (\$data['ops'] as \$i => \$op) {\n";
            $code .= "            \$right = \$this->convert(\$data['rights'][\$i]);\n";
            $code .= "            \$left = new \\PESM\\Parser\\AST\\BinaryOpNode(\$left, \$op['text'], \$right);\n";
            $code .= "        }\n";
            $code .= "        return \$left;\n";
            $code .= "    }\n\n";
            return $code;
        }
        
        // Generate conversion logic based on rule type
        switch ($info['type']) {
            case 'regex':
                $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(\$data['text']);\n";
                break;
                
            case 'oneOrMore':
            case 'zeroOrMore':
                $code .= "        \$items = [];\n";
                $code .= "        if (isset(\$data['statements'])) {\n";
                $code .= "            foreach (\$data['statements'] as \$stmt) {\n";
                $code .= "                \$node = isset(\$stmt['node']) ? \$stmt['node'] : \$stmt;\n";
                $code .= "                \$items[] = \$this->convert(\$node);\n";
                $code .= "            }\n";
                $code .= "        }\n";
                $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(\$items);\n";
                break;
                
            case 'choice':
                $code .= "        // Handle choice - unwrap to actual alternative\n";
                $code .= "        foreach (\$data as \$key => \$value) {\n";
                $code .= "            if (\$key !== 'text' && \$key !== '_matchrule' && \$key !== 'name' && \$key !== 'offset' && is_array(\$value)) {\n";
                $code .= "                return \$this->convert(\$value);\n";
                $code .= "            }\n";
                $code .= "        }\n";
                $code .= "        throw new \\Exception('No valid alternative found in choice');\n";
                break;
                
            default:
                // Sequence - extract components
                if (!empty($args)) {
                    $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(\n";
                    $argsList = [];
                    foreach ($args as $arg) {
                        $argsList[] = "            \$this->extractValue(\$data, '$arg')";
                    }
                    $code .= implode(",\n", $argsList) . "\n";
                    $code .= "        );\n";
                } else {
                    // Auto-detect arguments
                    $code .= "        \$args = \$this->extractArguments(\$data);\n";
                    $code .= "        return new \\PESM\\Parser\\AST\\{$nodeClass}(...\$args);\n";
                }
        }
        
        $code .= "    }\n\n";
        
        return $code;
    }
    
    /**
     * Generate helper methods
     */
    private function generateHelpers(): string
    {
        return <<<'PHP'
    /**
     * Detect rule type from array structure
     */
    private function detectType(array $data): string
    {
        // Check for _matchrule key (generated by parser)
        if (isset($data['_matchrule'])) {
            $type = $data['_matchrule'];
            
            // If it's Statement (choice without node), unwrap to alt
            if ($type === 'Statement' && isset($data['alt'])) {
                return $this->detectType($data['alt']);
            }
            
            return $type;
        }
        
        // Check for known keys
        $keys = array_keys($data);
        foreach ($keys as $key) {
            if ($key !== 'text' && !is_numeric($key)) {
                return $key;
            }
        }
        
        // Fallback to text-based detection
        if (isset($data['text'])) {
            $text = $data['text'];
            if (preg_match('/^[a-zA-Z_]/', $text)) {
                return 'Identifier';
            }
            if (is_numeric($text)) {
                return 'Number';
            }
        }
        
        throw new \Exception("Cannot detect type from data: " . json_encode($data));
    }
    
    /**
     * Extract value from data, converting if needed
     */
    private function extractValue(array $data, string $key)
    {
        if (isset($data[$key])) {
            $value = $data[$key];
            if (is_array($value)) {
                return $this->convert($value);
            }
            return $value;
        }
        
        // Try to find in nested structure
        foreach ($data as $k => $v) {
            if (is_array($v) && isset($v[$key])) {
                return $this->extractValue($v, $key);
            }
        }
        
        return null;
    }
    
    /**
     * Extract all arguments from data
     */
    private function extractArguments(array $data): array
    {
        $args = [];
        foreach ($data as $key => $value) {
            if ($key === 'text' || $key === '_matchrule' || $key === 'name' || $key === 'offset') continue;
            if (is_numeric($key)) continue;
            
            if (is_array($value)) {
                $args[] = $this->convert($value);
            } else {
                $args[] = $value;
            }
        }
        return $args;
    }

PHP;
    }
}
