<?php
/**
 * Generated AST Converter
 * DO NOT EDIT - Generated by ConverterGenerator
 */

namespace PESM\Parser;

use PESM\Parser\AST\Node;
use PESM\Parser\AST\ProgramNode;
use PESM\Parser\AST\AssignmentNode;
use PESM\Parser\AST\LiteralNode;
use PESM\Parser\AST\VariableNode;
use PESM\Parser\AST\IfNode;
use PESM\Parser\AST\ForeachNode;
use PESM\Parser\AST\MessageNode;
use PESM\Parser\AST\AcceptNode;
use PESM\Parser\AST\RefuseNode;

class GeneratedConverter
{
        /**
     * Convert parse result array to AST
     */
    public function convert($data): \PESM\Parser\AST\Node
    {
        if (!is_array($data)) {
            throw new \Exception("Invalid parse result");
        }
        
        // Unwrap Statement to alt if present
        if (isset($data['_matchrule']) && $data['_matchrule'] === 'Statement' && isset($data['alt'])) {
            $data = $data['alt'];
        }
        
        // Detect rule type from array structure
        $type = $this->detectType($data);
        $method = 'convert' . $type;
        
        if (!method_exists($this, $method)) {
            // No converter - try to unwrap to child
            return $this->unwrap($data);
        }
        
        return $this->$method($data);
    }
    
    /**
     * Unwrap intermediate nodes without converters
     */
    private function unwrap(array $data): \PESM\Parser\AST\Node
    {
        $type = $data['_matchrule'] ?? '';
        
        // Special handling for binary operations
        if (in_array($type, ['Additive', 'Multiplicative', 'Expression', 'Logical', 'Comparison'])) {
            // If has ops, build BinaryOpNode
            if (isset($data['ops']) && !empty($data['ops'])) {
                $left = $this->convert($data['left']);
                foreach ($data['ops'] as $i => $op) {
                    $right = $this->convert($data['rights'][$i]);
                    $left = new \PESM\Parser\AST\BinaryOpNode($left, $op['text'], $right);
                }
                return $left;
            }
            // No ops, unwrap to child
            if (isset($data['left'])) {
                return $this->convert($data['left']);
            }
            if (isset($data['value'])) {
                return $this->convert($data['value']);
            }
        }
        
        // Try to find first child node
        foreach ($data as $key => $value) {
            if ($key !== 'text' && $key !== '_matchrule' && $key !== 'name' && $key !== 'offset' && is_array($value)) {
                return $this->convert($value);
            }
        }
        throw new \Exception("Cannot unwrap node: " . json_encode($data));
    }
    
    /**
     * Convert Program to ProgramNode
     */
    private function convertProgram(array $data): \PESM\Parser\AST\ProgramNode
    {
        $items = [];
        if (isset($data['statements'])) {
            foreach ($data['statements'] as $stmt) {
                $node = isset($stmt['node']) ? $stmt['node'] : $stmt;
                $items[] = $this->convert($node);
            }
        }
        return new \PESM\Parser\AST\ProgramNode($items);
    }

    /**
     * Convert Assignment to AssignmentNode
     */
    private function convertAssignment(array $data): \PESM\Parser\AST\AssignmentNode
    {
        $varNode = $this->convert($data['var']);
        $exprNode = $data['expr']['value'] ?? $data['expr'];
        $exprNode = $this->convert($exprNode);
        return new \PESM\Parser\AST\AssignmentNode($varNode->name, $exprNode);
    }

    /**
     * Convert Number to LiteralNode
     */
    private function convertNumber(array $data): \PESM\Parser\AST\LiteralNode
    {
        return new \PESM\Parser\AST\LiteralNode($data['text']);
    }

    /**
     * Convert Identifier to VariableNode
     */
    private function convertIdentifier(array $data): \PESM\Parser\AST\VariableNode
    {
        return new \PESM\Parser\AST\VariableNode($data['text']);
    }

    /**
     * Convert IfStatement to IfNode
     */
    private function convertIfStatement(array $data): \PESM\Parser\AST\IfNode
    {
        $args = $this->extractArguments($data);
        return new \PESM\Parser\AST\IfNode(...$args);
    }

    /**
     * Convert ForeachStatement to ForeachNode
     */
    private function convertForeachStatement(array $data): \PESM\Parser\AST\ForeachNode
    {
        $args = $this->extractArguments($data);
        return new \PESM\Parser\AST\ForeachNode(...$args);
    }

    /**
     * Convert MessageStmt to MessageNode
     */
    private function convertMessageStmt(array $data): \PESM\Parser\AST\MessageNode
    {
        $args = $this->extractArguments($data);
        return new \PESM\Parser\AST\MessageNode(...$args);
    }

    /**
     * Convert AcceptStmt to AcceptNode
     */
    private function convertAcceptStmt(array $data): \PESM\Parser\AST\AcceptNode
    {
        $args = $this->extractArguments($data);
        return new \PESM\Parser\AST\AcceptNode(...$args);
    }

    /**
     * Convert RefuseStmt to RefuseNode
     */
    private function convertRefuseStmt(array $data): \PESM\Parser\AST\RefuseNode
    {
        $args = $this->extractArguments($data);
        return new \PESM\Parser\AST\RefuseNode(...$args);
    }

    /**
     * Convert String to LiteralNode
     */
    private function convertString(array $data): \PESM\Parser\AST\LiteralNode
    {
        $value = $data['value'] ?? $data['text'];
        return new \PESM\Parser\AST\LiteralNode($value);
    }

    /**
     * Detect rule type from array structure
     */
    private function detectType(array $data): string
    {
        // Check for _matchrule key (generated by parser)
        if (isset($data['_matchrule'])) {
            $type = $data['_matchrule'];
            
            // If it's Statement (choice without node), unwrap to alt
            if ($type === 'Statement' && isset($data['alt'])) {
                return $this->detectType($data['alt']);
            }
            
            return $type;
        }
        
        // Check for known keys
        $keys = array_keys($data);
        foreach ($keys as $key) {
            if ($key !== 'text' && !is_numeric($key)) {
                return $key;
            }
        }
        
        // Fallback to text-based detection
        if (isset($data['text'])) {
            $text = $data['text'];
            if (preg_match('/^[a-zA-Z_]/', $text)) {
                return 'Identifier';
            }
            if (is_numeric($text)) {
                return 'Number';
            }
        }
        
        throw new \Exception("Cannot detect type from data: " . json_encode($data));
    }
    
    /**
     * Extract value from data, converting if needed
     */
    private function extractValue(array $data, string $key)
    {
        if (isset($data[$key])) {
            $value = $data[$key];
            if (is_array($value)) {
                return $this->convert($value);
            }
            return $value;
        }
        
        // Try to find in nested structure
        foreach ($data as $k => $v) {
            if (is_array($v) && isset($v[$key])) {
                return $this->extractValue($v, $key);
            }
        }
        
        return null;
    }
    
    /**
     * Extract all arguments from data
     */
    private function extractArguments(array $data): array
    {
        $args = [];
        foreach ($data as $key => $value) {
            if ($key === 'text' || $key === '_matchrule' || $key === 'name' || $key === 'offset') continue;
            if (is_numeric($key)) continue;
            
            if (is_array($value)) {
                $args[] = $this->convert($value);
            } else {
                $args[] = $value;
            }
        }
        return $args;
    }
}
