<?php
/**
 * Generated AST Converter
 * DO NOT EDIT - Generated by ConverterGenerator
 */

namespace PESM\Parser;

use PESM\Parser\AST\Node;
use PESM\Parser\AST\ProgramNode;
use PESM\Parser\AST\FunctionDefNode;
use PESM\Parser\AST\ReturnNode;
use PESM\Parser\AST\AssignmentNode;
use PESM\Parser\AST\ArrayAccessNode;
use PESM\Parser\AST\UnaryOpNode;
use PESM\Parser\AST\ArrayLiteralNode;
use PESM\Parser\AST\ObjectLiteralNode;
use PESM\Parser\AST\FunctionCallNode;
use PESM\Parser\AST\LiteralNode;
use PESM\Parser\AST\VariableNode;
use PESM\Parser\AST\BlockNode;
use PESM\Parser\AST\IfNode;
use PESM\Parser\AST\ForeachNode;
use PESM\Parser\AST\WhileNode;
use PESM\Parser\AST\InterruptNode;
use PESM\Parser\AST\LabelNode;
use PESM\Parser\AST\GotoNode;

class GeneratedConverter
{
        /**
     * Convert parse result array to AST
     */
    public function convert($data): \PESM\Parser\AST\Node
    {
        if (!is_array($data)) {
            throw new \Exception("Invalid parse result");
        }
        
        // Unwrap Statement to alt if present
        if (isset($data['_matchrule']) && $data['_matchrule'] === 'Statement' && isset($data['alt'])) {
            $data = $data['alt'];
        }
        
        // Detect rule type from array structure
        $type = $this->detectType($data);
        $method = 'convert' . $type;
        
        if (!method_exists($this, $method)) {
            // No converter - try to unwrap to child
            return $this->unwrap($data);
        }
        
        return $this->$method($data);
    }
    
    /**
     * Unwrap intermediate nodes without converters
     */
    private function unwrap(array $data): \PESM\Parser\AST\Node
    {
        $type = $data['_matchrule'] ?? '';
        
        // Special handling for binary operations
        if (in_array($type, ['Additive', 'Multiplicative', 'Expression', 'Logical', 'Comparison'])) {
            // If has ops, build BinaryOpNode
            if (isset($data['ops']) && !empty($data['ops'])) {
                $left = $this->convert($data['left']);
                foreach ($data['ops'] as $i => $op) {
                    $right = $this->convert($data['rights'][$i]);
                    $left = new \PESM\Parser\AST\BinaryOpNode($left, $op['text'], $right);
                }
                return $left;
            }
            // No ops, unwrap to child
            if (isset($data['left'])) {
                return $this->convert($data['left']);
            }
            if (isset($data['value'])) {
                return $this->convert($data['value']);
            }
        }
        
        // Special handling for Unary
        if ($type === 'Unary') {
            if (isset($data['operator']) && isset($data['expr'])) {
                return new \PESM\Parser\AST\UnaryOpNode($data['operator'], $this->convert($data['expr']));
            }
            if (isset($data['node'])) {
                return $this->convert($data['node']);
            }
        }
        
        // Special handling for Postfix
        if ($type === 'Postfix') {
            if (isset($data['indices']) && !empty($data['indices'])) {
                $base = $this->convert($data['base']);
                foreach ($data['indices'] as $idx) {
                    $indexNode = $this->convert($idx);
                    $base = new \PESM\Parser\AST\ArrayAccessNode($base, $indexNode);
                }
                return $base;
            }
            if (isset($data['base'])) {
                return $this->convert($data['base']);
            }
        }
        
        // Try to find first child node
        foreach ($data as $key => $value) {
            if ($key !== 'text' && $key !== '_matchrule' && $key !== 'name' && $key !== 'offset' && is_array($value)) {
                return $this->convert($value);
            }
        }
        throw new \Exception("Cannot unwrap node: " . json_encode($data));
    }
    
    /**
     * Convert Program to ProgramNode
     */
    private function convertProgram(array $data): \PESM\Parser\AST\ProgramNode
    {
        $items = [];
        if (isset($data['statements'])) {
            foreach ($data['statements'] as $stmt) {
                $node = isset($stmt['node']) ? $stmt['node'] : $stmt;
                $items[] = $this->convert($node);
            }
        }
        return new \PESM\Parser\AST\ProgramNode($items);
    }

    /**
     * Convert FunctionDef to FunctionDefNode
     */
    private function convertFunctionDef(array $data): \PESM\Parser\AST\FunctionDefNode
    {
        $nameNode = $this->convert($data['fname']);
        $params = [];
        if (isset($data['params']['parameters'])) {
            foreach ($data['params']['parameters'] as $param) {
                $paramNode = $this->convert($param);
                $params[] = $paramNode->name;
            }
        }
        $body = [];
        if (isset($data['funcBody'])) {
            foreach ($data['funcBody'] as $stmt) {
                $node = isset($stmt['node']) ? $stmt['node'] : $stmt;
                $body[] = $this->convert($node);
            }
        }
        return new \PESM\Parser\AST\FunctionDefNode($nameNode->name, $params, $body);
    }

    /**
     * Convert ReturnStmt to ReturnNode
     */
    private function convertReturnStmt(array $data): \PESM\Parser\AST\ReturnNode
    {
        $expr = null;
        if (isset($data['expr'])) {
            $expr = $this->convert($data['expr']['value'] ?? $data['expr']);
        }
        return new \PESM\Parser\AST\ReturnNode($expr);
    }

    /**
     * Convert Assignment to AssignmentNode
     */
    private function convertAssignment(array $data): \PESM\Parser\AST\AssignmentNode
    {
        $varNode = $this->convert($data['var']);
        $exprNode = $data['expr']['value'] ?? $data['expr'];
        $exprNode = $this->convert($exprNode);
        // Support both simple variable and array access as lvalue
        $target = ($varNode instanceof \PESM\Parser\AST\VariableNode) ? $varNode->name : $varNode;
        return new \PESM\Parser\AST\AssignmentNode($target, $exprNode);
    }

    /**
     * Convert Postfix to ArrayAccessNode
     */
    private function convertPostfix(array $data): \PESM\Parser\AST\Node
    {
        $base = $this->convert($data['base']);
        if (!isset($data['indices']) || empty($data['indices'])) {
            return $base; // No indices, just return base
        }
        // Chain array access for multiple indices
        foreach ($data['indices'] as $idx) {
            $indexNode = $this->convert($idx);
            $base = new \PESM\Parser\AST\ArrayAccessNode($base, $indexNode);
        }
        return $base;
    }

    /**
     * Convert Unary to UnaryOpNode
     */
    private function convertUnary(array $data): \PESM\Parser\AST\Node
    {
        if (isset($data['operator']) && isset($data['expr'])) {
            $op = $data['operator'];
            $expr = $this->convert($data['expr']);
            return new \PESM\Parser\AST\UnaryOpNode($op, $expr);
        }
        if (isset($data['node'])) {
            return $this->convert($data['node']);
        }
        throw new \Exception('Invalid Unary node');
    }

    /**
     * Convert ArrayLiteral to ArrayLiteralNode
     */
    private function convertArrayLiteral(array $data): \PESM\Parser\AST\ArrayLiteralNode
    {
        $elements = [];
        if (isset($data['elements']['elements']) && is_array($data['elements']['elements'])) {
            foreach ($data['elements']['elements'] as $elem) {
                $elements[] = $this->convert($elem);
            }
        }
        return new \PESM\Parser\AST\ArrayLiteralNode($elements);
    }

    /**
     * Convert ObjectLiteral to ObjectLiteralNode
     */
    private function convertObjectLiteral(array $data): \PESM\Parser\AST\ObjectLiteralNode
    {
        $pairs = [];
        if (isset($data['pairs']['pairs']) && is_array($data['pairs']['pairs'])) {
            foreach ($data['pairs']['pairs'] as $pair) {
                $keyNode = $this->convert($pair['key']);
                $valueNode = $this->convert($pair['value']);
                $pairs[] = ['key' => $keyNode, 'value' => $valueNode];
            }
        }
        return new \PESM\Parser\AST\ObjectLiteralNode($pairs);
    }

    /**
     * Convert FunctionCall to FunctionCallNode
     */
    private function convertFunctionCall(array $data): \PESM\Parser\AST\FunctionCallNode
    {
        $nameNode = $this->convert($data['fname']);
        $args = [];
        if (isset($data['args']['arguments'])) {
            foreach ($data['args']['arguments'] as $arg) {
                $args[] = $this->convert($arg);
            }
        }
        return new \PESM\Parser\AST\FunctionCallNode($nameNode->name, $args);
    }

    /**
     * Convert String to LiteralNode
     */
    private function convertString(array $data): \PESM\Parser\AST\LiteralNode
    {
        $value = $data['value'] ?? $data['text'];
        return new \PESM\Parser\AST\LiteralNode($value);
    }

    /**
     * Convert Number to LiteralNode
     */
    private function convertNumber(array $data): \PESM\Parser\AST\LiteralNode
    {
        return new \PESM\Parser\AST\LiteralNode($data['text']);
    }

    /**
     * Convert Identifier to VariableNode
     */
    private function convertIdentifier(array $data): \PESM\Parser\AST\VariableNode
    {
        $text = $data['text'] ?? $data[0]['text'] ?? '';
        return new \PESM\Parser\AST\VariableNode($text);
    }

    /**
     * Convert Block to BlockNode
     */
    private function convertBlock(array $data): \PESM\Parser\AST\BlockNode
    {
        $stmts = [];
        if (isset($data['statements'])) {
            foreach ($data['statements'] as $stmt) {
                $node = isset($stmt['node']) ? $stmt['node'] : $stmt;
                $stmts[] = $this->convert($node);
            }
        }
        return new \PESM\Parser\AST\BlockNode($stmts);
    }

    /**
     * Convert IfStatement to IfNode
     */
    private function convertIfStatement(array $data): \PESM\Parser\AST\IfNode
    {
        $cond = $this->convert($data['cond']['value'] ?? $data['cond']);
        $thenBody = [];
        if (isset($data['thenBody'])) {
            foreach ($data['thenBody'] as $item) {
                // Check if it's a Block node
                if (isset($item['_matchrule']) && $item['_matchrule'] === 'Block') {
                    $blockNode = $this->convert($item);
                    $thenBody = array_merge($thenBody, $blockNode->statements);
                } else {
                    $node = isset($item['node']) ? $item['node'] : $item;
                    $thenBody[] = $this->convert($node);
                }
            }
        }
        $elseBody = [];
        if (isset($data['elseBody'])) {
            foreach ($data['elseBody'] as $item) {
                if (isset($item['_matchrule']) && $item['_matchrule'] === 'Block') {
                    $blockNode = $this->convert($item);
                    $elseBody = array_merge($elseBody, $blockNode->statements);
                } else {
                    $node = isset($item['node']) ? $item['node'] : $item;
                    $elseBody[] = $this->convert($node);
                }
            }
        }
        return new \PESM\Parser\AST\IfNode($cond, $thenBody, $elseBody);
    }

    /**
     * Convert ForeachStatement to ForeachNode
     */
    private function convertForeachStatement(array $data): \PESM\Parser\AST\ForeachNode
    {
        $varNode = $this->convert($data['var']);
        $from = $this->convert($data['from']['value'] ?? $data['from']);
        $to = $this->convert($data['to']['value'] ?? $data['to']);
        $body = [];
        if (isset($data['loopBody'])) {
            foreach ($data['loopBody'] as $stmt) {
                $node = isset($stmt['node']) ? $stmt['node'] : $stmt;
                $body[] = $this->convert($node);
            }
        }
        // ForeachNode expects (var, iterable, body) but grammar has from/to
        // Create range array
        return new \PESM\Parser\AST\ForeachNode($varNode->name, new \PESM\Parser\AST\BinaryOpNode($from, 'range', $to), $body);
    }

    /**
     * Convert WhileStatement to WhileNode
     */
    private function convertWhileStatement(array $data): \PESM\Parser\AST\WhileNode
    {
        $cond = $this->convert($data['cond']['value'] ?? $data['cond']);
        $body = [];
        if (isset($data['loopBody'])) {
            foreach ($data['loopBody'] as $stmt) {
                $node = isset($stmt['node']) ? $stmt['node'] : $stmt;
                $body[] = $this->convert($node);
            }
        }
        return new \PESM\Parser\AST\WhileNode($cond, $body);
    }

    /**
     * Convert MessageStmt to InterruptNode
     */
    private function convertMessageStmt(array $data): \PESM\Parser\AST\InterruptNode
    {
        $arg = isset($data['msg']) ? $this->convert($data['msg']['value'] ?? $data['msg']) : null;
        return new \PESM\Parser\AST\InterruptNode('message', $arg);
    }

    /**
     * Convert AcceptStmt to InterruptNode
     */
    private function convertAcceptStmt(array $data): \PESM\Parser\AST\InterruptNode
    {
        $arg = isset($data['state']) ? $this->convert($data['state']['value'] ?? $data['state']) : null;
        return new \PESM\Parser\AST\InterruptNode('accept', $arg);
    }

    /**
     * Convert RefuseStmt to InterruptNode
     */
    private function convertRefuseStmt(array $data): \PESM\Parser\AST\InterruptNode
    {
        $arg = isset($data['state']) ? $this->convert($data['state']['value'] ?? $data['state']) : null;
        return new \PESM\Parser\AST\InterruptNode('refuse', $arg);
    }

    /**
     * Convert LabelStmt to LabelNode
     */
    private function convertLabelStmt(array $data): \PESM\Parser\AST\LabelNode
    {
        $labelNode = $this->convert($data['label']);
        return new \PESM\Parser\AST\LabelNode($labelNode->name);
    }

    /**
     * Convert GotoStmt to GotoNode
     */
    private function convertGotoStmt(array $data): \PESM\Parser\AST\GotoNode
    {
        $labelNode = $this->convert($data['label']);
        return new \PESM\Parser\AST\GotoNode($labelNode->name);
    }

    /**
     * Detect rule type from array structure
     */
    private function detectType(array $data): string
    {
        // Check for _matchrule key (generated by parser)
        if (isset($data['_matchrule'])) {
            $type = $data['_matchrule'];
            
            // If it's Statement (choice without node), unwrap to alt
            if ($type === 'Statement' && isset($data['alt'])) {
                return $this->detectType($data['alt']);
            }
            
            return $type;
        }
        
        // Check for known keys
        $keys = array_keys($data);
        foreach ($keys as $key) {
            if ($key !== 'text' && !is_numeric($key)) {
                return $key;
            }
        }
        
        // Fallback to text-based detection
        if (isset($data['text'])) {
            $text = $data['text'];
            if (preg_match('/^[a-zA-Z_]/', $text)) {
                return 'Identifier';
            }
            if (is_numeric($text)) {
                return 'Number';
            }
        }
        
        throw new \Exception("Cannot detect type from data: " . json_encode($data));
    }
    
    /**
     * Extract value from data, converting if needed
     */
    private function extractValue(array $data, string $key)
    {
        if (isset($data[$key])) {
            $value = $data[$key];
            if (is_array($value)) {
                return $this->convert($value);
            }
            return $value;
        }
        
        // Try to find in nested structure
        foreach ($data as $k => $v) {
            if (is_array($v) && isset($v[$key])) {
                return $this->extractValue($v, $key);
            }
        }
        
        return null;
    }
    
    /**
     * Extract all arguments from data
     */
    private function extractArguments(array $data): array
    {
        $args = [];
        foreach ($data as $key => $value) {
            if ($key === 'text' || $key === '_matchrule' || $key === 'name' || $key === 'offset') continue;
            if (is_numeric($key)) continue;
            
            if (is_array($value)) {
                $args[] = $this->convert($value);
            } else {
                $args[] = $value;
            }
        }
        return $args;
    }
}
