<?php
namespace PESM\Parser;

/**
 * MonarchGenerator
 *
 * Generate a minimal Monarch definition and an editor scaffold (examples/editor)
 * from a PEG grammar file. This is intentionally simple: it extracts keywords
 * and quoted tokens and emits a Monarch JS file, a validate.php endpoint and
 * a small demo page.
 */
class MonarchGenerator
{
    protected string $grammarPath;

    public function __construct(string $grammarPath)
    {
        $this->grammarPath = $grammarPath;
    }

    public function generate(string $outDir): void
    {
        if (!is_readable($this->grammarPath)) {
            throw new \RuntimeException("Grammar not found: {$this->grammarPath}");
        }

        $text = file_get_contents($this->grammarPath);

        // extract keywords from Keyword: (...) rule
        $keywords = [];
        if (preg_match('/Keyword:\s*\(([^\)]*)\)/s', $text, $m)) {
            $inside = $m[1];
            if (preg_match_all('/"([A-Z_][A-Z0-9_]*)"/', $inside, $km)) {
                $keywords = array_values(array_unique($km[1]));
            }
        }

        // all quoted tokens
        $quoted = [];
        if (preg_match_all('/"([^"\\\\]+)"/', $text, $qm)) {
            $quoted = array_values(array_unique($qm[1]));
        }

        // operators: quoted tokens that are not keywords and look like symbols/short
        $operators = array_filter($quoted, function ($t) use ($keywords) {
            if (in_array($t, $keywords, true)) return false;
            if (preg_match('/[^A-Za-z0-9]/', $t)) return true;
            if (strlen($t) <= 2) return true;
            return false;
        });

        if (!is_dir($outDir)) mkdir($outDir, 0755, true);

        file_put_contents(rtrim($outDir, '/') . '/monarch.generated.js', $this->buildMonarch($keywords, $operators));
        file_put_contents(rtrim($outDir, '/') . '/validate.php', $this->buildValidatePhp());
        file_put_contents(rtrim($outDir, '/') . '/index.html', $this->buildIndexHtml());
        file_put_contents(rtrim($outDir, '/') . '/editor.js', $this->buildEditorJs());
    }

    protected function buildMonarch(array $keywords, array $operators): string
    {
        $kw = json_encode(array_values($keywords));
        $ops = json_encode(array_values($operators));

        $template = <<<'JS'
// Auto-generated by MonarchGenerator
monaco.languages.register({ id: 'pesm' });

monaco.languages.setMonarchTokensProvider('pesm', {
  defaultToken: '',
  tokenPostfix: '.pesm',
  keywords: __KW__,
  operators: __OPS__,
  symbols: /[=><!~?:&|+\-*\/\^%]+/,
  tokenizer: {
    root: [
      [/\s+/, 'white'],
      [/\/\/.*$/, 'comment'],
      [/\/\*/, { token: 'comment', next: '@comment' }],
      [/\"([^\"\\]|\\.)*\"/, 'string'],
      [/\d+(\.\d+)?/, 'number'],
      [/[A-Za-z_][A-Za-z0-9_]*/, {
        cases: {
          '@keywords': 'keyword',
          '@default': 'identifier'
        }
      }],
      [/[{}()\[\]]/, '@brackets'],
      [/[;,.]/, 'delimiter'],
      [/@symbols/, 'operator']
    ],
    comment: [
      [/[^\/*]+/, 'comment'],
      [/\*\//, 'comment', '@pop'],
      [/[\/*]/, 'comment']
    ]
  }
});

monaco.languages.setLanguageConfiguration('pesm', {
  comments: { lineComment: '//', blockComment: ['/*','*/'] },
  brackets: [['{','}'],['[',']'],['(',')']],
  autoClosingPairs: [{open:'"',close:'"'},{open:'(',close:')'},{open:'[',close:']'},{open:'{',close:'}'}],
  surroundingPairs: [{open:'"',close:'"'},{open:'(',close:')'}],
  folding: { offSide: false }
});

JS;

        return str_replace(['__KW__','__OPS__'], [$kw, $ops], $template);
    }

    protected function buildValidatePhp(): string
    {
        return <<<'PHP'
<?php
header('Content-Type: application/json');
require __DIR__ . '/../../vendor/autoload.php';

use PESM\ScriptEngine;

try {
    if (empty($_POST) && $_SERVER['REQUEST_METHOD'] !== 'POST') {
        echo json_encode(['markers' => []]);
        exit;
    }

    $code = $_POST['code'] ?? file_get_contents('php://input');

    if (empty(trim($code))) {
        echo json_encode(['markers' => []]);
        exit;
    }

    $engine = new ScriptEngine();

    try {
        $bytecode = $engine->compile($code);
        echo json_encode(['markers' => []]);
        exit;
        
    } catch (\Exception $e) {
        $msg = $e->getMessage();
        
        // Try to get line from error message
        $line = 1;
        if (preg_match('/line (\d+)/i', $msg, $m)) {
            $line = (int)$m[1];
        } elseif (preg_match('/Undefined function: func_(\w+)/i', $msg, $m)) {
            // For undefined function errors, find the line where it's called
            $funcName = $m[1];
            $lines = explode("\n", $code);
            foreach ($lines as $i => $lineContent) {
                if (preg_match('/\b' . preg_quote($funcName, '/') . '\s*\(/i', $lineContent)) {
                    $line = $i + 1;
                    break;
                }
            }
        }
        // Note: For parse errors without line info, we mark line 1
        // PESM parser doesn't provide detailed position information
        
        $lines = explode("\n", $code);
        $lineContent = $lines[$line - 1] ?? '';
        $endCol = strlen($lineContent) + 1;
        
        $marker = [
            'startLineNumber' => $line,
            'startColumn' => 1,
            'endLineNumber' => $line,
            'endColumn' => $endCol,
            'message' => $msg,
            'severity' => 'error'
        ];
        echo json_encode(['markers' => [$marker]]);
        exit;
    }

} catch (\Throwable $t) {
  echo json_encode(['markers' => [[
    'startLineNumber' => 1,
    'startColumn' => 1,
    'endLineNumber' => 1,
    'endColumn' => 100,
    'message' => $t->getMessage(),
    'severity' => 'error'
  ]]]);
}

PHP;
    }

    protected function buildIndexHtml(): string
    {
        return <<<'HTML'
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>PESM Editor Demo</title>
  <style>
    html, body { height: 100%; margin: 0; padding: 0; font-family: sans-serif; }
    #toolbar { padding: 8px; background: #f3f3f3; border-bottom: 1px solid #ddd; }
    #toolbar button { padding: 6px 12px; cursor: pointer; }
    #container { height: calc(100% - 41px); }
  </style>
  <script src="https://cdn.jsdelivr.net/npm/monaco-editor@0.39.0/min/vs/loader.js"></script>
</head>
<body>
  <div id="toolbar">
    <button id="validate">Validate</button>
    <span id="status" style="margin-left: 10px;"></span>
  </div>
  <div id="container"></div>
  <script>
    require.config({ paths: { 'vs': 'https://cdn.jsdelivr.net/npm/monaco-editor@0.39.0/min/vs' } });
    require(['vs/editor/editor.main'], function() {
      // Load monarch and editor after Monaco is ready
      const script1 = document.createElement('script');
      script1.src = 'monarch.generated.js';
      document.body.appendChild(script1);
      
      script1.onload = function() {
        const script2 = document.createElement('script');
        script2.src = 'editor.js';
        document.body.appendChild(script2);
      };
    });
  </script>
</body>
</html>
HTML;
    }

    protected function buildEditorJs(): string
    {
        return <<<'JS'
// Monaco is already loaded, create editor directly
const defaultCode = `// PESM Script Example
name = "World"
age = 25

IF age >= 18
    status = "Adult"
ELSE
    status = "Minor"
END

MESSAGE "Hello " + name + "! Status: " + status
`;

const model = monaco.editor.createModel(defaultCode, 'pesm');
const editor = monaco.editor.create(document.getElementById('container'), {
  model: model,
  automaticLayout: true,
  minimap: { enabled: false },
  theme: 'vs-dark'
});

const statusEl = document.getElementById('status');

const validate = () => {
  statusEl.textContent = 'Validating...';
  statusEl.style.color = '#666';

  const code = model.getValue();

  fetch('validate.php', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: 'code=' + encodeURIComponent(code)
  }).then(r => r.json()).then(data => {
    const markers = (data.markers || []).map(m => ({
      startLineNumber: m.startLineNumber || 1,
      startColumn: m.startColumn || 1,
      endLineNumber: m.endLineNumber || 1,
      endColumn: m.endColumn || 100,
      message: m.message || 'error',
      severity: (m.severity === 'warning') ? monaco.MarkerSeverity.Warning : monaco.MarkerSeverity.Error
    }));
    monaco.editor.setModelMarkers(model, 'pesm', markers);
    
    if (markers.length === 0) {
      statusEl.textContent = '✓ No errors';
      statusEl.style.color = 'green';
    } else {
      statusEl.textContent = `✗ ${markers.length} error(s)`;
      statusEl.style.color = 'red';
    }
  }).catch(err => {
    monaco.editor.setModelMarkers(model, 'pesm', [{
      startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 100,
      message: err.message, severity: monaco.MarkerSeverity.Error
    }]);
    statusEl.textContent = '✗ Validation failed';
    statusEl.style.color = 'red';
  });
};

document.getElementById('validate').addEventListener('click', validate);

// Auto-validate on load
setTimeout(validate, 500);
JS;
    }
}
